version: '3'
services:
  front:
    image: austsxk/${SERVICE_NAME}_${ARCH}:${FRONT_SERVICE_VERSION}
    container_name: ${SERVICE_NAME}
    restart: always
    volumes:
      - ${CONFIG_PATH}/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${PORT}:80