apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-test
  name: busybox-test
spec:
  containers:
  - image: busybox:latest
    name: busybox-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
