version: '3.7'
services:
  mon:
    image: quay.io/ceph/ceph:v17.2.6
    container_name: ceph-mon
    network_mode: host
    privileged: true
    restart: always
    volumes:
      - ./data:/var/lib/ceph
      - ./ceph.conf:/etc/ceph/ceph.conf
      - ./mon-entrypoint.sh:/entrypoint.sh
    command: bash /entrypoint.sh
  

  mgr:
    image: quay.io/ceph/ceph:v17.2.6
    container_name: ceph-mgr
    network_mode: host
    restart: always
    privileged: true
    depends_on: [mon]
    volumes:
      - ./data:/var/lib/ceph
      - ./ceph.conf:/etc/ceph/ceph.conf
    command: ceph-mgr -i mgr --foreground

  osd:
    image: quay.io/ceph/ceph:v17.2.6
    container_name: ceph-osd
    restart: always
    network_mode: host
    privileged: true
    depends_on: [mon]
    volumes:
      - ./osd:/var/lib/ceph/osd
      - ./ceph.conf:/etc/ceph/ceph.conf
    command: bash -c "
      mkdir -p /var/lib/ceph/osd/ceph-0 &&
      ceph-osd -i 0 --mkfs --osd-uuid=$(uuidgen) &&
      ceph-osd -i 0 --foreground"

  mds:
    image: quay.io/ceph/ceph:v17.2.6
    container_name: ceph-mds
    network_mode: host
    restart: always
    privileged: true
    depends_on: [mon]
    volumes:
      - ./data:/var/lib/ceph
      - ./ceph.conf:/etc/ceph/ceph.conf
    command: ceph-mds -i mds-a --foreground