# Generated by Django 4.2.21 on 2025-06-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=64)),
                ("date", models.DateField()),
                ("breakfast", models.BooleanField(default=False)),
                ("lunch", models.BooleanField(default=False)),
                ("dinner", models.BooleanField(default=False)),
                ("exercise", models.BooleanField(default=False)),
                ("sleep", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "checkin",
            },
        ),
    ]
