version: '3'

services:
  ollama:
    image: ollama/ollama:0.9.1-rc0
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ${MODEL_PATH}:/root/.ollama/models
    restart: always

#  openwebui:
#    image: ghcr.io/open-webui/open-webui:main
#    container_name: open-webui
#    ports:
#      - "3888:8080"
#    environment:
#      - OLLAMA_BASE_URL=http://ollama:11434
#      - WEBUI_AUTH=False
#      - WEBUI_SECRET_KEY=qy0000
#    depends_on:
#      - ollama
#    restart: always

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports:
      - "3888:8080"
    environment:
      - OLLAMA_API=http://ollama:11434/api
      - DISABLE_AUTH=true
      - DEFAULT_MODEL=deepseek-r1:1.5b
    depends_on:
      - ollama
    restart: always