version: '3'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    ports:
      - "${MinioAPIPort}:9000"
      - "${MinioConsolePort}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data

  minio_endpoint:
    image: "${REGISTRY_REPO}/${PROJECT_NAME}/minio_endpoint_${ARCH}:${MinioServerVersion}"
    working_dir: /app
    container_name: minio_endpoint
    restart: always
    privileged: true
    ports:
      - "${MinioServerPort}:9115"
    healthcheck:
      test: [ "CMD-SHELL", "python --version" ]
      interval: 1s
      timeout: 10s
      retries: 2
      start_period: 1s
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}
      - LOCAL_GROUP_ID=${LOCAL_GROUP_ID}
      - TZ=Asia/Shanghai
    volumes:
      - ${MinioServerConfigPath}:/app/config/.env
